# Generated by Django 2.2.3 on 2019-07-29 17:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name your appointment', max_length=50, verbose_name='Name')),
                ('descriptions', models.TextField(help_text='Enter necessary details about your appointment', verbose_name='Description')),
                ('datetime', models.DateTimeField(help_text='Date and time of the appointment', verbose_name='Date and time')),
                ('place', django.contrib.gis.db.models.fields.PointField(help_text='Place where meet', srid=4326, verbose_name='Place')),
            ],
        ),
    ]
