# Generated by Django 2.2.3 on 2019-08-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetpage', '0002_shortcut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='descriptions',
            new_name='description',
        ),
    ]
