# Generated by Django 2.2.4 on 2019-08-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetpage', '0003_auto_20190803_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, help_text='Enter necessary details about your appointment', verbose_name='Description'),
        ),
    ]
