# Generated by Django 2.2.4 on 2019-08-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetpage', '0004_auto_20190817_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='address',
        ),
    ]
